# Generated by Django 2.2.7 on 2020-03-28 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_number', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Pentadbiran', 'Pentadbiran'), ('Operasi', 'Operasi'), ('Pembangunan', 'Pembangunan'), ('Pelanggan', 'Pelanggan')], max_length=100)),
                ('checkout_on', models.DateTimeField(blank=True, null=True)),
                ('overdue', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=True)),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['overdue', 'id', 'department', '-checkout_on'],
            },
        ),
    ]
