# Generated by Django 2.2.7 on 2020-03-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200330_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-overdue', 'id', 'department', '-checkout_on'], 'permissions': [('can_login', 'can login')]},
        ),
    ]
