# Generated by Django 2.2.7 on 2020-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makmal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='result_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
